# Seu exemplo de string com caracteres problemáticos
example_string = "SUM\u00c1RIO\nNote que a lista de exemplos abaixo n\u00e3o contempla todas as poss\u00edveis condi\u00e7\u00f5es cl\u00ednicas.\nSUBST\u00c2NCIAS E M\u00c9TODOS PROIBIDOS EM TODO TEMPO\nS0 Subst\u00e2ncias N\u00e3o Aprovadas 4\nS1 Agentes Anabolizantes 5\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados\npara o tratamento de hipogonadismo masculino, por exemplo.\nS2 Horm\u00f4nios pept\u00eddicos, fatores de crescimento, subst\u00e2ncias relacionadas e mim\u00e9ticos 7\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados\npara o tratamento de, por exemplo, anemia, hipogonadismo masculino, defici\u00eancia de horm\u00f4nio do\ncrescimento.\nS3 Beta-2 agonistas 9\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados\npara o tratamento de, por exemplo, asma e outras doen\u00e7as respirat\u00f3rias.\nS4 Horm\u00f4nios e moduladores metab\u00f3licos 10\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados para\no tratamento de, por exemplo, c\u00e2ncer de mama, diabetes, infertilidade (feminina), s\u00edndrome do ov\u00e1rio\npolic\u00edstico.\nS5 Diur\u00e9ticos e agentes mascarantes 12\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados para\no tratamento de, por exemplo, insufici\u00eancia card\u00edaca, hipertens\u00e3o.\nM1 \u2013 M2 \u2013 M3 M\u00e9todos Proibidos 13\nSUBST\u00c2NCIAS E M\u00c9TODOS PROIBIDOS EM COMPETI\u00c7\u00c3O\nS6 Estimulantes 14\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados\npara o tratamento de, por exemplo, anafilaxia, transtornos de d\u00e9ficit de aten\u00e7\u00e3o e hiperatividade (TDAH),\nsintomas de resfriado e gripe.\nS7 Narc\u00f3ticos 16\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados para\no tratamento de, por exemplo, dor, incluindo les\u00f5es musculoesquel\u00e9ticas.\nS8 Canabinoides 17\nS9 Glicocorticoides 18\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados para\no tratamento de, por exemplo, alergia, anafilaxia, asma, s\u00edndrome do intestino irrit\u00e1vel.\nSUBST\u00c2NCIAS PROIBIDAS EM ESPORTES ESPEC\u00cdFICOS\nP1 Betabloqueadores 19\nAlgumas dessas subst\u00e2ncias podem ser encontradas em, mas n\u00e3o se limitam a, medicamentos usados para\no tratamento de, por exemplo, insufici\u00eancia card\u00edaca, hipertens\u00e3o.\n\u00cdndice Remissivo 20"

# Função para corrigir caracteres problemáticos em uma string
def fix_string(string):
    return string.encode('raw_unicode_escape').decode('unicode-escape')

# Corrigindo a string de exemplo
fixed_example = fix_string(example_string)

print(fixed_example)